import DashboardLayout from '@/components/DashboardLayout';
import StatusDashboard from '@/components/StatusDashboard';
import RoadmapView from '@/components/RoadmapView';
import FeatureRoadmap from '@/components/FeatureRoadmap';
import EpicRoadmap from '@/components/EpicRoadmap';
import ReleaseDashboard from '@/components/ReleaseDashboard';
import RoadmapGuide from '@/pages/RoadmapGuide';

// Import mock seed data (temporary - will be replaced with real Jira data)
import { featureRoadmapMock } from '@/data/featureRoadmapMock';
import { epicRoadmapMock } from '@/data/epicRoadmapMock';
import { releaseDashboardMock } from '@/data/releaseDashboardMock';
import { 
  initiativeMetricsMock, 
  businessRequestMetricsMock 
} from '@/data/portfolioMetricsMock';

// Legacy inline mock data - replaced by organized files
/*
const mockFeatures: Feature[] = [
  {
    id: 'feat-1',
    title: 'Customer Portal Modernization',
    themeName: 'Digital Transformation',
    startDate: new Date('2024-01-15'),
    endDate: new Date('2024-06-30'),
    completionPercentage: 62,
    status: 'in-progress',
    epicCount: 5,
    completedEpics: 3,
    owner: 'Sarah Johnson',
    description: 'Modernize customer-facing portal with new UI/UX and enhanced features',
  },
  {
    id: 'feat-2',
    title: 'API Integration Platform',
    themeName: 'Digital Transformation',
    startDate: new Date('2024-02-01'),
    endDate: new Date('2024-08-31'),
    completionPercentage: 35,
    status: 'in-progress',
    epicCount: 4,
    completedEpics: 1,
    owner: 'Michael Chen',
    description: 'Build unified API gateway for third-party integrations',
  },
  {
    id: 'feat-3',
    title: 'Security Compliance Framework',
    themeName: 'Security Enhancement',
    startDate: new Date('2024-03-01'),
    endDate: new Date('2024-09-30'),
    completionPercentage: 29,
    status: 'in-progress',
    epicCount: 3,
    completedEpics: 0,
    owner: 'David Park',
    description: 'Implement GDPR and SOC2 compliance measures',
  },
  {
    id: 'feat-4',
    title: 'Cloud Infrastructure Migration',
    themeName: 'Infrastructure Optimization',
    startDate: new Date('2024-04-01'),
    endDate: new Date('2024-12-31'),
    completionPercentage: 15,
    status: 'not-started',
    epicCount: 6,
    completedEpics: 0,
    owner: 'Emily Rodriguez',
    description: 'Migrate on-premise infrastructure to AWS cloud',
  },
  {
    id: 'feat-5',
    title: 'Mobile App Launch',
    themeName: 'Digital Transformation',
    startDate: new Date('2024-05-01'),
    endDate: new Date('2024-11-30'),
    completionPercentage: 0,
    status: 'not-started',
    epicCount: 4,
    completedEpics: 0,
    owner: 'James Wilson',
    description: 'Launch native mobile applications for iOS and Android',
  },
  {
    id: 'feat-6',
    title: 'Data Analytics Platform',
    themeName: 'Digital Transformation',
    startDate: new Date('2024-01-01'),
    endDate: new Date('2024-05-31'),
    completionPercentage: 85,
    status: 'in-progress',
    epicCount: 3,
    completedEpics: 2,
    owner: 'Lisa Anderson',
    description: 'Real-time analytics and business intelligence platform',
  },
];

const mockEpics: Epic[] = [
  {
    id: 'epic-1',
    title: 'SSO Integration',
    featureName: 'Customer Portal Modernization',
    themeName: 'Digital Transformation',
    startDate: new Date('2024-01-15'),
    endDate: new Date('2024-03-31'),
    completionPercentage: 100,
    status: 'done',
    storyCount: 8,
    completedStories: 8,
    owner: 'John Smith',
    description: 'Implement Single Sign-On with OAuth2 and SAML support',
  },
  {
    id: 'epic-2',
    title: 'User Profile Management',
    featureName: 'Customer Portal Modernization',
    themeName: 'Digital Transformation',
    startDate: new Date('2024-02-01'),
    endDate: new Date('2024-04-30'),
    completionPercentage: 85,
    status: 'in-progress',
    storyCount: 12,
    completedStories: 10,
    owner: 'Sarah Johnson',
    description: 'Enhanced user profile with preferences and customization',
  },
  {
    id: 'epic-3',
    title: 'API Gateway Setup',
    featureName: 'API Integration Platform',
    themeName: 'Digital Transformation',
    startDate: new Date('2024-02-01'),
    endDate: new Date('2024-05-31'),
    completionPercentage: 45,
    status: 'in-progress',
    storyCount: 15,
    completedStories: 7,
    owner: 'Michael Chen',
    description: 'Build and deploy API gateway infrastructure',
  },
  {
    id: 'epic-4',
    title: 'Third-party Connectors',
    featureName: 'API Integration Platform',
    themeName: 'Digital Transformation',
    startDate: new Date('2024-04-01'),
    endDate: new Date('2024-07-31'),
    completionPercentage: 20,
    status: 'in-progress',
    storyCount: 18,
    completedStories: 4,
    owner: 'David Park',
    description: 'Pre-built connectors for popular services',
  },
  {
    id: 'epic-5',
    title: 'GDPR Compliance',
    featureName: 'Security Compliance Framework',
    themeName: 'Security Enhancement',
    startDate: new Date('2024-03-01'),
    endDate: new Date('2024-06-30'),
    completionPercentage: 35,
    status: 'in-progress',
    storyCount: 14,
    completedStories: 5,
    owner: 'Emily Rodriguez',
    description: 'Implement GDPR data protection requirements',
  },
  {
    id: 'epic-6',
    title: 'SOC2 Audit Preparation',
    featureName: 'Security Compliance Framework',
    themeName: 'Security Enhancement',
    startDate: new Date('2024-05-01'),
    endDate: new Date('2024-09-30'),
    completionPercentage: 15,
    status: 'not-started',
    storyCount: 20,
    completedStories: 0,
    owner: 'David Park',
    description: 'Prepare systems and documentation for SOC2 audit',
  },
  {
    id: 'epic-7',
    title: 'AWS Migration Phase 1',
    featureName: 'Cloud Infrastructure Migration',
    themeName: 'Infrastructure Optimization',
    startDate: new Date('2024-04-01'),
    endDate: new Date('2024-07-31'),
    completionPercentage: 0,
    status: 'not-started',
    storyCount: 25,
    completedStories: 0,
    owner: 'James Wilson',
    description: 'Migrate web application tier to AWS',
  },
  {
    id: 'epic-8',
    title: 'Real-time Data Pipeline',
    featureName: 'Data Analytics Platform',
    themeName: 'Digital Transformation',
    startDate: new Date('2024-01-01'),
    endDate: new Date('2024-03-31'),
    completionPercentage: 100,
    status: 'done',
    storyCount: 10,
    completedStories: 10,
    owner: 'Lisa Anderson',
    description: 'Build real-time data ingestion and processing pipeline',
  },
  {
    id: 'epic-9',
    title: 'Analytics Dashboard',
    featureName: 'Data Analytics Platform',
    themeName: 'Digital Transformation',
    startDate: new Date('2024-03-01'),
    endDate: new Date('2024-05-31'),
    completionPercentage: 70,
    status: 'in-progress',
    storyCount: 16,
    completedStories: 11,
    owner: 'Lisa Anderson',
    description: 'Interactive analytics dashboards with customizable widgets',
  },
  {
    id: 'epic-10',
    title: 'iOS App Development',
    featureName: 'Mobile App Launch',
    themeName: 'Digital Transformation',
    startDate: new Date('2024-05-01'),
    endDate: new Date('2024-09-30'),
    completionPercentage: 0,
    status: 'not-started',
    storyCount: 22,
    completedStories: 0,
    owner: 'James Wilson',
    description: 'Native iOS application development',
  },
  {
    id: 'epic-11',
    title: 'Android App Development',
    featureName: 'Mobile App Launch',
    themeName: 'Digital Transformation',
    startDate: new Date('2024-06-01'),
    endDate: new Date('2024-10-31'),
    completionPercentage: 0,
    status: 'not-started',
    storyCount: 22,
    completedStories: 0,
    owner: 'Sarah Johnson',
    description: 'Native Android application development',
  },
  {
    id: 'epic-12',
    title: 'Password Reset Flow',
    featureName: 'Customer Portal Modernization',
    themeName: 'Digital Transformation',
    startDate: new Date('2024-03-15'),
    endDate: new Date('2024-04-30'),
    completionPercentage: 60,
    status: 'in-progress',
    storyCount: 6,
    completedStories: 4,
    owner: 'Mike Davis',
    description: 'Secure password reset with email verification',
  },
  {
    id: 'epic-13',
    title: 'Notification System',
    featureName: 'Customer Portal Modernization',
    themeName: 'Digital Transformation',
    startDate: new Date('2024-05-01'),
    endDate: new Date('2024-06-30'),
    completionPercentage: 25,
    status: 'blocked',
    storyCount: 9,
    completedStories: 2,
    owner: 'Tom Wilson',
    description: 'Real-time in-app notifications and email alerts',
  },
];

const mockStories: Story[] = [
  // Version 1.0 - Released
  {
    id: 's1',
    key: 'PROJ-101',
    title: 'Implement OAuth2 authentication flow',
    status: 'done',
    priority: 'high',
    assignee: 'John Smith',
    fixVersion: 'v1.0',
    storyPoints: 8,
    epicName: 'User Authentication',
    featureName: 'Security & Access Control',
    businessRequestName: 'Customer Portal Modernization',
    subtaskAssignees: ['John Smith', 'Sarah Jones', 'Mike Davis'],
    subtasks: [
      { id: 'st1', key: 'PROJ-101-1', title: 'Design OAuth2 flow diagram', status: 'done', assignee: 'John Smith' },
      { id: 'st2', key: 'PROJ-101-2', title: 'Implement authorization endpoint', status: 'done', assignee: 'Sarah Jones' },
      { id: 'st3', key: 'PROJ-101-3', title: 'Add token validation', status: 'done', assignee: 'Mike Davis' },
    ],
  },
  {
    id: 's2',
    key: 'PROJ-102',
    title: 'Create user registration form',
    status: 'done',
    priority: 'high',
    assignee: 'Sarah Jones',
    fixVersion: 'v1.0',
    storyPoints: 5,
    epicName: 'User Authentication',
    featureName: 'Security & Access Control',
    businessRequestName: 'Customer Portal Modernization',
    subtaskAssignees: ['Sarah Jones', 'Emily Chen'],
  },
  {
    id: 's3',
    key: 'PROJ-103',
    title: 'Add password reset functionality',
    status: 'done',
    priority: 'medium',
    assignee: 'Mike Davis',
    fixVersion: 'v1.0',
    storyPoints: 3,
    epicName: 'User Authentication',
    featureName: 'Security & Access Control',
    businessRequestName: 'Customer Portal Modernization',
    subtaskAssignees: ['Mike Davis'],
  },
  {
    id: 's4',
    key: 'PROJ-104',
    title: 'Design dashboard landing page',
    status: 'done',
    priority: 'medium',
    assignee: 'Emily Chen',
    fixVersion: 'v1.0',
    storyPoints: 5,
    epicName: 'Dashboard UI',
    featureName: 'User Experience Enhancement',
    businessRequestName: 'Customer Portal Modernization',
    subtaskAssignees: ['Emily Chen', 'Tom Wilson'],
  },
  {
    id: 's5',
    key: 'PROJ-105',
    title: 'Implement basic charts and graphs',
    status: 'done',
    priority: 'low',
    assignee: 'Tom Wilson',
    fixVersion: 'v1.0',
    storyPoints: 8,
    epicName: 'Dashboard UI',
    featureName: 'User Experience Enhancement',
    businessRequestName: 'Customer Portal Modernization',
    subtaskAssignees: ['Tom Wilson', 'John Smith', 'Lisa Anderson'],
  },

  // Version 1.1 - In Progress
  {
    id: 's6',
    key: 'PROJ-201',
    title: 'Add real-time data sync',
    status: 'done',
    priority: 'high',
    assignee: 'John Smith',
    fixVersion: 'v1.1',
    storyPoints: 13,
    epicName: 'Real-time Features',
    featureName: 'Live Data Streaming',
    businessRequestName: 'Real-time Analytics Dashboard',
    subtaskAssignees: ['John Smith', 'Sarah Jones', 'David Park'],
  },
  {
    id: 's7',
    key: 'PROJ-202',
    title: 'Implement WebSocket connection',
    status: 'in-progress',
    priority: 'high',
    assignee: 'Sarah Jones',
    fixVersion: 'v1.1',
    storyPoints: 8,
    epicName: 'Real-time Features',
    featureName: 'Live Data Streaming',
    businessRequestName: 'Real-time Analytics Dashboard',
    subtaskAssignees: ['Sarah Jones', 'Mike Davis'],
    subtasks: [
      { id: 'st4', key: 'PROJ-202-1', title: 'Setup WebSocket server', status: 'done', assignee: 'Sarah Jones' },
      { id: 'st5', key: 'PROJ-202-2', title: 'Implement client connection handler', status: 'in-progress', assignee: 'Mike Davis' },
      { id: 'st6', key: 'PROJ-202-3', title: 'Add heartbeat mechanism', status: 'todo', assignee: 'Sarah Jones' },
      { id: 'st7', key: 'PROJ-202-4', title: 'Create reconnection logic', status: 'todo' },
    ],
  },
  {
    id: 's8',
    key: 'PROJ-203',
    title: 'Add notification system',
    status: 'in-progress',
    priority: 'medium',
    assignee: 'Mike Davis',
    fixVersion: 'v1.1',
    storyPoints: 5,
    epicName: 'Notifications',
    featureName: 'Alert & Notification Engine',
    businessRequestName: 'Real-time Analytics Dashboard',
    subtaskAssignees: ['Mike Davis', 'Emily Chen', 'Tom Wilson'],
  },
  {
    id: 's9',
    key: 'PROJ-204',
    title: 'Create email notification templates',
    status: 'todo',
    priority: 'medium',
    assignee: 'Emily Chen',
    fixVersion: 'v1.1',
    storyPoints: 3,
    epicName: 'Notifications',
    featureName: 'Alert & Notification Engine',
    businessRequestName: 'Real-time Analytics Dashboard',
    subtaskAssignees: ['Emily Chen'],
  },
  {
    id: 's10',
    key: 'PROJ-205',
    title: 'Implement push notifications',
    status: 'todo',
    priority: 'low',
    assignee: 'Tom Wilson',
    fixVersion: 'v1.1',
    storyPoints: 5,
    epicName: 'Notifications',
    featureName: 'Alert & Notification Engine',
    businessRequestName: 'Real-time Analytics Dashboard',
    subtaskAssignees: ['Tom Wilson', 'Sarah Jones'],
  },
  {
    id: 's11',
    key: 'PROJ-206',
    title: 'Add user preferences for notifications',
    status: 'blocked',
    priority: 'medium',
    fixVersion: 'v1.1',
    storyPoints: 3,
    epicName: 'Notifications',
    featureName: 'Alert & Notification Engine',
    businessRequestName: 'Real-time Analytics Dashboard',
    subtaskAssignees: ['David Park', 'Emily Chen'],
  },

  // Version 2.0 - Planned
  {
    id: 's12',
    key: 'PROJ-301',
    title: 'Design new reporting interface',
    status: 'todo',
    priority: 'high',
    assignee: 'Sarah Jones',
    fixVersion: 'v2.0',
    storyPoints: 8,
    epicName: 'Advanced Reporting',
    featureName: 'Business Intelligence Suite',
    businessRequestName: 'API Integration Platform',
    subtaskAssignees: ['Sarah Jones', 'Emily Chen', 'Lisa Anderson'],
  },
  {
    id: 's13',
    key: 'PROJ-302',
    title: 'Implement custom report builder',
    status: 'todo',
    priority: 'high',
    assignee: 'John Smith',
    fixVersion: 'v2.0',
    storyPoints: 13,
    epicName: 'Advanced Reporting',
    featureName: 'Business Intelligence Suite',
    businessRequestName: 'API Integration Platform',
    subtaskAssignees: ['John Smith', 'Mike Davis', 'Tom Wilson'],
    subtasks: [
      { id: 'st8', key: 'PROJ-302-1', title: 'Design report builder UI', status: 'todo', assignee: 'John Smith' },
      { id: 'st9', key: 'PROJ-302-2', title: 'Create drag-and-drop components', status: 'todo', assignee: 'Mike Davis' },
      { id: 'st10', key: 'PROJ-302-3', title: 'Implement data source selector', status: 'todo', assignee: 'Tom Wilson' },
      { id: 'st11', key: 'PROJ-302-4', title: 'Add preview functionality', status: 'todo' },
      { id: 'st12', key: 'PROJ-302-5', title: 'Implement save/load templates', status: 'todo', assignee: 'John Smith' },
    ],
  },
  {
    id: 's14',
    key: 'PROJ-303',
    title: 'Add export to PDF functionality',
    status: 'todo',
    priority: 'medium',
    assignee: 'Mike Davis',
    fixVersion: 'v2.0',
    storyPoints: 5,
    epicName: 'Advanced Reporting',
    featureName: 'Business Intelligence Suite',
    businessRequestName: 'API Integration Platform',
    subtaskAssignees: ['Mike Davis', 'Sarah Jones'],
  },
  {
    id: 's15',
    key: 'PROJ-304',
    title: 'Implement scheduled reports',
    status: 'todo',
    priority: 'medium',
    fixVersion: 'v2.0',
    storyPoints: 8,
    epicName: 'Advanced Reporting',
    featureName: 'Business Intelligence Suite',
    businessRequestName: 'API Integration Platform',
    subtaskAssignees: ['Tom Wilson', 'David Park'],
  },
  {
    id: 's16',
    key: 'PROJ-305',
    title: 'Add multi-tenant support',
    status: 'todo',
    priority: 'high',
    assignee: 'Emily Chen',
    fixVersion: 'v2.0',
    storyPoints: 21,
    epicName: 'Platform Infrastructure',
    featureName: 'Enterprise Architecture',
    businessRequestName: 'Security Compliance Framework',
    subtaskAssignees: ['Emily Chen', 'John Smith', 'David Park', 'Michael Chen'],
  },
  {
    id: 's17',
    key: 'PROJ-306',
    title: 'Implement role-based access control',
    status: 'todo',
    priority: 'high',
    assignee: 'Tom Wilson',
    fixVersion: 'v2.0',
    storyPoints: 13,
    epicName: 'Platform Infrastructure',
    featureName: 'Enterprise Architecture',
    businessRequestName: 'Security Compliance Framework',
    subtaskAssignees: ['Tom Wilson', 'Mike Davis', 'Emily Chen'],
  },
];
*/

export default function Dashboard() {
  return (
    <DashboardLayout
      statusContent={
        <StatusDashboard 
          initiatives={initiativeMetricsMock}
          businessRequests={businessRequestMetricsMock}
        />
      }
      roadmapContent={<RoadmapView />}
      featureRoadmapContent={<FeatureRoadmap features={featureRoadmapMock} />}
      epicRoadmapContent={<EpicRoadmap epics={epicRoadmapMock} />}
      storyCompletionContent={<ReleaseDashboard stories={releaseDashboardMock} />}
      roadmapGuideContent={<RoadmapGuide />}
    />
  );
}
