import DashboardLayout from '@/components/DashboardLayout';
import StatusDashboard from '@/components/StatusDashboard';
import RoadmapView from '@/components/RoadmapView';
import FeatureRoadmap, { Feature } from '@/components/FeatureRoadmap';
import ReleaseDashboard, { Story } from '@/components/ReleaseDashboard';

//todo: remove mock functionality - replace with real Jira data
const mockFeatures: Feature[] = [
  {
    id: 'feat-1',
    title: 'Customer Portal Modernization',
    themeName: 'Digital Transformation',
    startDate: new Date('2024-01-15'),
    endDate: new Date('2024-06-30'),
    completionPercentage: 62,
    status: 'in-progress',
    epicCount: 5,
    completedEpics: 3,
    owner: 'Sarah Johnson',
    description: 'Modernize customer-facing portal with new UI/UX and enhanced features',
  },
  {
    id: 'feat-2',
    title: 'API Integration Platform',
    themeName: 'Digital Transformation',
    startDate: new Date('2024-02-01'),
    endDate: new Date('2024-08-31'),
    completionPercentage: 35,
    status: 'in-progress',
    epicCount: 4,
    completedEpics: 1,
    owner: 'Michael Chen',
    description: 'Build unified API gateway for third-party integrations',
  },
  {
    id: 'feat-3',
    title: 'Security Compliance Framework',
    themeName: 'Security Enhancement',
    startDate: new Date('2024-03-01'),
    endDate: new Date('2024-09-30'),
    completionPercentage: 29,
    status: 'in-progress',
    epicCount: 3,
    completedEpics: 0,
    owner: 'David Park',
    description: 'Implement GDPR and SOC2 compliance measures',
  },
  {
    id: 'feat-4',
    title: 'Cloud Infrastructure Migration',
    themeName: 'Infrastructure Optimization',
    startDate: new Date('2024-04-01'),
    endDate: new Date('2024-12-31'),
    completionPercentage: 15,
    status: 'not-started',
    epicCount: 6,
    completedEpics: 0,
    owner: 'Emily Rodriguez',
    description: 'Migrate on-premise infrastructure to AWS cloud',
  },
  {
    id: 'feat-5',
    title: 'Mobile App Launch',
    themeName: 'Digital Transformation',
    startDate: new Date('2024-05-01'),
    endDate: new Date('2024-11-30'),
    completionPercentage: 0,
    status: 'not-started',
    epicCount: 4,
    completedEpics: 0,
    owner: 'James Wilson',
    description: 'Launch native mobile applications for iOS and Android',
  },
  {
    id: 'feat-6',
    title: 'Data Analytics Platform',
    themeName: 'Digital Transformation',
    startDate: new Date('2024-01-01'),
    endDate: new Date('2024-05-31'),
    completionPercentage: 85,
    status: 'in-progress',
    epicCount: 3,
    completedEpics: 2,
    owner: 'Lisa Anderson',
    description: 'Real-time analytics and business intelligence platform',
  },
];

const mockStories: Story[] = [
  // Version 1.0 - Released
  {
    id: 's1',
    key: 'PROJ-101',
    title: 'Implement OAuth2 authentication flow',
    status: 'done',
    priority: 'high',
    assignee: 'John Smith',
    fixVersion: 'v1.0',
    storyPoints: 8,
    epicName: 'User Authentication',
    featureName: 'Security & Access Control',
    businessRequestName: 'Customer Portal Modernization',
    subtaskAssignees: ['John Smith', 'Sarah Jones', 'Mike Davis'],
  },
  {
    id: 's2',
    key: 'PROJ-102',
    title: 'Create user registration form',
    status: 'done',
    priority: 'high',
    assignee: 'Sarah Jones',
    fixVersion: 'v1.0',
    storyPoints: 5,
    epicName: 'User Authentication',
    featureName: 'Security & Access Control',
    businessRequestName: 'Customer Portal Modernization',
    subtaskAssignees: ['Sarah Jones', 'Emily Chen'],
  },
  {
    id: 's3',
    key: 'PROJ-103',
    title: 'Add password reset functionality',
    status: 'done',
    priority: 'medium',
    assignee: 'Mike Davis',
    fixVersion: 'v1.0',
    storyPoints: 3,
    epicName: 'User Authentication',
    featureName: 'Security & Access Control',
    businessRequestName: 'Customer Portal Modernization',
    subtaskAssignees: ['Mike Davis'],
  },
  {
    id: 's4',
    key: 'PROJ-104',
    title: 'Design dashboard landing page',
    status: 'done',
    priority: 'medium',
    assignee: 'Emily Chen',
    fixVersion: 'v1.0',
    storyPoints: 5,
    epicName: 'Dashboard UI',
    featureName: 'User Experience Enhancement',
    businessRequestName: 'Customer Portal Modernization',
    subtaskAssignees: ['Emily Chen', 'Tom Wilson'],
  },
  {
    id: 's5',
    key: 'PROJ-105',
    title: 'Implement basic charts and graphs',
    status: 'done',
    priority: 'low',
    assignee: 'Tom Wilson',
    fixVersion: 'v1.0',
    storyPoints: 8,
    epicName: 'Dashboard UI',
    featureName: 'User Experience Enhancement',
    businessRequestName: 'Customer Portal Modernization',
    subtaskAssignees: ['Tom Wilson', 'John Smith', 'Lisa Anderson'],
  },

  // Version 1.1 - In Progress
  {
    id: 's6',
    key: 'PROJ-201',
    title: 'Add real-time data sync',
    status: 'done',
    priority: 'high',
    assignee: 'John Smith',
    fixVersion: 'v1.1',
    storyPoints: 13,
    epicName: 'Real-time Features',
    featureName: 'Live Data Streaming',
    businessRequestName: 'Real-time Analytics Dashboard',
    subtaskAssignees: ['John Smith', 'Sarah Jones', 'David Park'],
  },
  {
    id: 's7',
    key: 'PROJ-202',
    title: 'Implement WebSocket connection',
    status: 'in-progress',
    priority: 'high',
    assignee: 'Sarah Jones',
    fixVersion: 'v1.1',
    storyPoints: 8,
    epicName: 'Real-time Features',
    featureName: 'Live Data Streaming',
    businessRequestName: 'Real-time Analytics Dashboard',
    subtaskAssignees: ['Sarah Jones', 'Mike Davis'],
  },
  {
    id: 's8',
    key: 'PROJ-203',
    title: 'Add notification system',
    status: 'in-progress',
    priority: 'medium',
    assignee: 'Mike Davis',
    fixVersion: 'v1.1',
    storyPoints: 5,
    epicName: 'Notifications',
    featureName: 'Alert & Notification Engine',
    businessRequestName: 'Real-time Analytics Dashboard',
    subtaskAssignees: ['Mike Davis', 'Emily Chen', 'Tom Wilson'],
  },
  {
    id: 's9',
    key: 'PROJ-204',
    title: 'Create email notification templates',
    status: 'todo',
    priority: 'medium',
    assignee: 'Emily Chen',
    fixVersion: 'v1.1',
    storyPoints: 3,
    epicName: 'Notifications',
    featureName: 'Alert & Notification Engine',
    businessRequestName: 'Real-time Analytics Dashboard',
    subtaskAssignees: ['Emily Chen'],
  },
  {
    id: 's10',
    key: 'PROJ-205',
    title: 'Implement push notifications',
    status: 'todo',
    priority: 'low',
    assignee: 'Tom Wilson',
    fixVersion: 'v1.1',
    storyPoints: 5,
    epicName: 'Notifications',
    featureName: 'Alert & Notification Engine',
    businessRequestName: 'Real-time Analytics Dashboard',
    subtaskAssignees: ['Tom Wilson', 'Sarah Jones'],
  },
  {
    id: 's11',
    key: 'PROJ-206',
    title: 'Add user preferences for notifications',
    status: 'blocked',
    priority: 'medium',
    fixVersion: 'v1.1',
    storyPoints: 3,
    epicName: 'Notifications',
    featureName: 'Alert & Notification Engine',
    businessRequestName: 'Real-time Analytics Dashboard',
    subtaskAssignees: ['David Park', 'Emily Chen'],
  },

  // Version 2.0 - Planned
  {
    id: 's12',
    key: 'PROJ-301',
    title: 'Design new reporting interface',
    status: 'todo',
    priority: 'high',
    assignee: 'Sarah Jones',
    fixVersion: 'v2.0',
    storyPoints: 8,
    epicName: 'Advanced Reporting',
    featureName: 'Business Intelligence Suite',
    businessRequestName: 'API Integration Platform',
    subtaskAssignees: ['Sarah Jones', 'Emily Chen', 'Lisa Anderson'],
  },
  {
    id: 's13',
    key: 'PROJ-302',
    title: 'Implement custom report builder',
    status: 'todo',
    priority: 'high',
    assignee: 'John Smith',
    fixVersion: 'v2.0',
    storyPoints: 13,
    epicName: 'Advanced Reporting',
    featureName: 'Business Intelligence Suite',
    businessRequestName: 'API Integration Platform',
    subtaskAssignees: ['John Smith', 'Mike Davis', 'Tom Wilson'],
  },
  {
    id: 's14',
    key: 'PROJ-303',
    title: 'Add export to PDF functionality',
    status: 'todo',
    priority: 'medium',
    assignee: 'Mike Davis',
    fixVersion: 'v2.0',
    storyPoints: 5,
    epicName: 'Advanced Reporting',
    featureName: 'Business Intelligence Suite',
    businessRequestName: 'API Integration Platform',
    subtaskAssignees: ['Mike Davis', 'Sarah Jones'],
  },
  {
    id: 's15',
    key: 'PROJ-304',
    title: 'Implement scheduled reports',
    status: 'todo',
    priority: 'medium',
    fixVersion: 'v2.0',
    storyPoints: 8,
    epicName: 'Advanced Reporting',
    featureName: 'Business Intelligence Suite',
    businessRequestName: 'API Integration Platform',
    subtaskAssignees: ['Tom Wilson', 'David Park'],
  },
  {
    id: 's16',
    key: 'PROJ-305',
    title: 'Add multi-tenant support',
    status: 'todo',
    priority: 'high',
    assignee: 'Emily Chen',
    fixVersion: 'v2.0',
    storyPoints: 21,
    epicName: 'Platform Infrastructure',
    featureName: 'Enterprise Architecture',
    businessRequestName: 'Security Compliance Framework',
    subtaskAssignees: ['Emily Chen', 'John Smith', 'David Park', 'Michael Chen'],
  },
  {
    id: 's17',
    key: 'PROJ-306',
    title: 'Implement role-based access control',
    status: 'todo',
    priority: 'high',
    assignee: 'Tom Wilson',
    fixVersion: 'v2.0',
    storyPoints: 13,
    epicName: 'Platform Infrastructure',
    featureName: 'Enterprise Architecture',
    businessRequestName: 'Security Compliance Framework',
    subtaskAssignees: ['Tom Wilson', 'Mike Davis', 'Emily Chen'],
  },
];

export default function Dashboard() {
  return (
    <DashboardLayout
      statusContent={<StatusDashboard />}
      roadmapContent={<RoadmapView />}
      featureRoadmapContent={<FeatureRoadmap features={mockFeatures} />}
      storyCompletionContent={<ReleaseDashboard stories={mockStories} />}
    />
  );
}
